### PR TITLE
initial AT24C512 eeprom. Need pi4j change to complete

### PR DESCRIPTION
**Pull request by taartspi**

### CODE REVIEW

**Comment by eitch** [comment]
@taartspi i see you need a change in pi4j for this to work, do you know where and how? Maybe you have a PR i can look at?

**Comment by taartspi** [comment]
PS As you can see that that eeprom code is not complete as I couldn't test.  If you wanted  'working' test code I think I can use my IKA-Logic device to simulate the master and complete the device, although it might require less effort to just modify the Pi4j code.   Also, this is a problem I found out of interest, it is not preventing any work completion.

**Comment by taartspi** [comment]
@eitch

**Comment by eitch** [comment]
maybe @savageautomate can give some input. I don't know yet how we would go about adding multi byte addresses... I suppose it depends if pigpio supports it...

**Comment by taartspi** [comment]
I will first investigate the two byte register.   I looked at pigpio docs and they only support one byte regs and enhancement in linuxfs makes more sense.   Looking at the bcm docs i think the SOC macros will support this.  I was last digging into the pi4j code to understand the JNI and how the structure written to the file is created. Any pointers on this ?  (poor PUN)

**Comment by eitch** [comment]
@taartspi so pointers:
https://github.com/Pi4J/pi4j-v2/blob/develop/libraries/pi4j-library-linuxfs/src/main/native/com_pi4j_library_linuxfs_internal_LinuxFS.h
https://github.com/Pi4J/pi4j-v2/blob/develop/plugins/pi4j-plugin-linuxfs/src/main/java/com/pi4j/plugin/linuxfs/provider/i2c/LinuxFsI2C.java

but i don't have much more =)

**Comment by taartspi** [comment]
Good day.  Been looking in those and specs. Pigpio doesn’t support multi byte reg so i think linuxfs s the place to enhance. To experiment i added a new method into the interfaces which as implemented means the gpio and raspi would also see that addition, this is not good but i will wait to get something functional before we talk about the correct way go add a unique method to only one i2c provider.   I think in the lower level code this will require use of ioctl passing multiple messages in a single call so the driver uses a restart.   
thankyou for the pointers. When i have something that works i will push it so we can discuss the correct way to proceed   @eitch

**Pull request merged**
